### ISSUE TITLE
Ablation on Source of Vocabulary

### ISSUE THREAD

**Issue by hellerguyh** [xushilin1/dst-det#1]
Hello,

Thank you for sharing your insightful work. Regarding the ablation study on the vocabulary source (Table 2f), did you utilize the 21K categories from ImageNet-21K or the 1K subset from ILSVRC?

**Comment by lxtGH** [comment]
Hello, thanks for your attention to our work. We use 21K categories for ablation studies. Due to computation cost, we only verify this on LVIS. I believe it will work well on V3Det or more large vocabulary size datasets.
